/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.compiladorn.gui;

import br.com.compiladorn.analisadorlexico.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StringReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ximenes
 */
public class AnalisadorLexicoGui extends javax.swing.JFrame {
    
    JFileChooser fileChooser;
    String textoFonte = "";
    
    /**
     * Creates new form AnalisadorLexicoGUI
     */
    public AnalisadorLexicoGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEntrada = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButtonAnalisar = new javax.swing.JButton();
        jTextFieldGramatica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonArquivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(93, 64, 55));
        jPanel1.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(50, 25, 17));

        jLabelTitulo.setBackground(new java.awt.Color(254, 254, 254));
        jLabelTitulo.setFont(new java.awt.Font("Roboto Mono Medium", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(254, 254, 254));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Conversor JFlex");
        jLabelTitulo.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));

        jPanel4.setBackground(new java.awt.Color(64, 196, 255));
        jPanel4.setBorder(null);

        jTextAreaEntrada.setColumns(20);
        jTextAreaEntrada.setRows(5);
        jTextAreaEntrada.setToolTipText("");
        jScrollPane1.setViewportView(jTextAreaEntrada);

        jLabel2.setFont(new java.awt.Font("Roboto Mono Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Entrada");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(64, 196, 255));
        jPanel6.setBorder(null);

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSaida);

        jLabel5.setFont(new java.awt.Font("Roboto Mono Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Saida");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4))
        );

        jButtonAnalisar.setFont(new java.awt.Font("Roboto Mono Medium", 0, 12)); // NOI18N
        jButtonAnalisar.setText("Analisar");
        jButtonAnalisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAnalisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAnalisar)
                .addContainerGap())
        );

        jTextFieldGramatica.setBackground(new java.awt.Color(93, 64, 55));
        jTextFieldGramatica.setForeground(new java.awt.Color(224, 224, 224));
        jTextFieldGramatica.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(93, 64, 55));
        jLabel1.setFont(new java.awt.Font("Roboto Mono Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Entrada");

        jButtonArquivo.setBackground(new java.awt.Color(93, 64, 55));
        jButtonArquivo.setForeground(new java.awt.Color(254, 254, 254));
        jButtonArquivo.setText(" ... ");
        jButtonArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGramatica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonArquivo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGramatica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonArquivo))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonAnalisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalisarActionPerformed
        if (jTextAreaEntrada.isEnabled()) {
            textoFonte = jTextAreaEntrada.getText();
        }
        
        try {
            analisarCodigo();
        } catch (Exception ex) {
            Logger.getLogger(AnalisadorLexicoGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAnalisarActionPerformed

    private void analisarCodigo() throws IOException{
        String path = this.jTextAreaEntrada.getText();
        String resultado = "";
        int linha = 1;
        
        AnalisadorLexico aLex;
        aLex = new AnalisadorLexico(new StringReader(path));
        
        while (true) {
            Token token = aLex.yylex();
            if (token == null) {
                System.out.println(resultado);
                jTextAreaSaida.setText(resultado);

                return;
            }
            switch (token) {

                case OPERADOR_ARITMETICO:
                    resultado = resultado + "Linha: " + linha + "<Operador_Aritmético> " + aLex.lexeme + "\n";
                    break;

                case OPERADOR_LOGICO:
                    resultado = resultado + "Linha: " + linha + "<Operador_Lógico> " + aLex.lexeme + "\n";
                    break;

                case ATRIBUICAO:
                    resultado = resultado + "Linha: " + linha + "<Operador_Atribuição> " + aLex.lexeme + "\n";
                    break;
                case FIM_COMANDO:
                    resultado = resultado + "Linha: " + linha + "<Fim_comando> " + aLex.lexeme + "\n";
                    break;
                case OPERADOR_RELACIONAL:
                    resultado = resultado + "Linha: " + linha + "<Operador_Relacional> " + aLex.lexeme + "\n";
                    break;

                case COMENTARIO:
                    resultado = resultado + "Linha: " + linha + "<Comentario> " + aLex.lexeme + "\n";
                    break;

                case LINHA:
                    break;

                case ERROR:                  
                    resultado = resultado + "Erro na linha " + linha + ": Símbolo não reconhecido: " + aLex.lexeme + "\n";
                    break;

                case ID:
                    resultado = resultado + "Linha: " + linha + "<ID> " + aLex.lexeme + "\n";
                    break;

                case NUMEROS_REIAS:
                    resultado = resultado + "Linha: " + linha + "<Numeros_reais> " + aLex.lexeme + "\n";
                    break;
                case TEXTO:
                    resultado = resultado + "Linha: " + linha + "<Texto> " + aLex.lexeme + "\n";
                    break;
                case THEN:
                    resultado = resultado + "Linha: " + linha + "<Então> " + aLex.lexeme + "\n";
                    break;
                case WHILE:
                    resultado = resultado + "Linha: " + linha + "<Laço> " + aLex.lexeme + "\n";
                    break;
                case FOR:
                    resultado = resultado + "Linha: " + linha + "<Laço> " + aLex.lexeme + "\n";
                    break;
                case IF:
                    resultado = resultado + "Linha: " + linha + "<Condicional> " + aLex.lexeme + "\n";
                    break;
                case NUMEROS_NATURAIS:
                    resultado = resultado + "Linha: " + linha + "<Numero> " + aLex.lexeme + "\n";
                    break;

                case INICIO_BLOCO:
                    resultado = resultado + "Linha: " + linha + "<Inicio_algoritmo>" + aLex.lexeme + "\n";
                    break;
                case BRANCO:
                    //resultado = resultado + "Linha: " + cont + "<Fim_algoritmo>" + lexical.lexeme + "\n";
                    break;
                case FIM_BLOCO:
                    resultado = resultado + "Linha: " + linha + "<Fim_algoritmo>" + aLex.lexeme + "\n";
                    break;

                default:
                    resultado = resultado + "Linha: " + linha + "<" + aLex.lexeme + ">" + linha++;
                    break;
            }
            linha++;
        }
    }
    
    private void jButtonArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArquivoActionPerformed
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos txt", "txt"));
        int i = fileChooser.showSaveDialog(null);
        String resul = "";
        
        try (Scanner scanner =  new Scanner(fileChooser.getSelectedFile())){
            while (scanner.hasNextLine()){
              resul = resul + scanner.nextLine() +"\n";
            }      
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AnalisadorLexicoGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextFieldGramatica.setText(fileChooser.getSelectedFile().getPath());
        
        jTextAreaEntrada.setText(resul);
        //jButtonAnalisar.setEnabled(gerarGramatica(fileChooser.getSelectedFile()));
    }//GEN-LAST:event_jButtonArquivoActionPerformed

    private boolean gerarGramatica(File file){
        try{
            GeradorAnalisadorLexico.gerar(file);
            return true;
        }catch(Exception e){
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalisar;
    private javax.swing.JButton jButtonArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaEntrada;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldGramatica;
    // End of variables declaration//GEN-END:variables
}
