
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.com.compiladorn.analisadorsintatico;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int OPERADOR_PROD = 21;
  public static final int FUNCAO = 26;
  public static final int L_CHAVE = 11;
  public static final int PROGRAM_BEGIN = 2;
  public static final int R_CHAVE = 12;
  public static final int FUNCAO_PARAMETRO = 19;
  public static final int FOR = 15;
  public static final int E = 28;
  public static final int OPERADOR_SOMA = 23;
  public static final int OPERADOR_SUB = 24;
  public static final int IGUAL = 29;
  public static final int OU = 27;
  public static final int NUMEROS_REAIS = 7;
  public static final int IF = 14;
  public static final int EXPOENTE = 18;
  public static final int EOF = 0;
  public static final int MAIOR = 32;
  public static final int PVIRGULA = 25;
  public static final int error = 1;
  public static final int BRANCO = 17;
  public static final int MENOR = 31;
  public static final int L_PARENTESIS = 9;
  public static final int VARIAVEL = 4;
  public static final int NUMEROS_NATURAIS = 5;
  public static final int PROGRAM_END = 3;
  public static final int ELSE = 8;
  public static final int OPERADOR_DIV = 22;
  public static final int WHILE = 16;
  public static final int DECL_FUNCAO_PARAMETRO = 20;
  public static final int ATRIBUICAO = 13;
  public static final int R_PARENTESIS = 10;
  public static final int NAO_IGUAL = 30;
  public static final int TEXTO = 6;
  public static final int MENOR_IGUAL = 33;
  public static final int NAO = 35;
  public static final int MAIOR_IGUAL = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM_BEGIN",
  "PROGRAM_END",
  "VARIAVEL",
  "NUMEROS_NATURAIS",
  "TEXTO",
  "NUMEROS_REAIS",
  "ELSE",
  "L_PARENTESIS",
  "R_PARENTESIS",
  "L_CHAVE",
  "R_CHAVE",
  "ATRIBUICAO",
  "IF",
  "FOR",
  "WHILE",
  "BRANCO",
  "EXPOENTE",
  "FUNCAO_PARAMETRO",
  "DECL_FUNCAO_PARAMETRO",
  "OPERADOR_PROD",
  "OPERADOR_DIV",
  "OPERADOR_SOMA",
  "OPERADOR_SUB",
  "PVIRGULA",
  "FUNCAO",
  "OU",
  "E",
  "IGUAL",
  "NAO_IGUAL",
  "MENOR",
  "MAIOR",
  "MENOR_IGUAL",
  "MAIOR_IGUAL",
  "NAO"
  };
}

